--- # --- VDN specific parameters ---
agent: rnn # Default rnn agent

# use epsilon greedy action selector
action_selector: epsilon_greedy
buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: q
learner: q_learner
double_q: True
mixer: vdn

name: vdn
