env: lbf

env_args:
  field_size: 5
  players: 2
  max_food: 2
  force_coop: True
  partiteammate_observe: False
  is_print: False
  seed: 1024
  need_render: False
  remote: False
  render_output_path: logs

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 10000000

# make these parameters shared within one environment
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 1000000

z_dim: 8
n_sub_modules: 4
